export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
export const WORKSPACE_COLLECTION_ID =
    process.env.NEXT_PUBLIC_APPWRITE_COLLECTIONS_WORKSPACES_ID!;
export const IMAGES_BUCKET_ID =
    process.env.NEXT_PUBLIC_APPWRITE_IMAGES_BUCKET_ID!;
