export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
export const WORKSPACE_COLLECTION_ID =
    process.env.NEXT_PUBLIC_APPWRITE_COLLECTIONS_WORKSPACES_ID!;
export const MEMBERS_COLLETION_ID =
    process.env.NEXT_PUBLIC_APPWRITE_COLLECTIONS_MEMBERS_ID!;
export const PROJECTS_COLLECTION_ID =
    process.env.NEXT_PUBLIC_APPWRITE_COLLECTIONS_PROJECTS_ID!;
export const IMAGES_BUCKET_ID =
    process.env.NEXT_PUBLIC_APPWRITE_IMAGES_BUCKET_ID!;
export const TASKS_COLLECTION_ID =
    process.env.NEXT_PUBLIC_APPWRITE_COLLECTIONS_TASKS_ID!;
